# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  new_relic_license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  domain_name: localhost:3000
  rollbar:
    server_side_token: <%= ENV["ROLLBAR_SERVER_SIDE_TOKEN"] %>
    client_side_token: <%= ENV["ROLLBAR_CLIENT_SIDE_TOKEN"] %>

development:
  <<: *default
  secret_key_base: 9290d2182611415e12cbd92a1dc60d211dcdb6e1b47dfc0025185dd5cdd84c543be880d5460bbe786563f6caa3802f56dd8af946c6eb91999f2e26f7c574ee70
  domain_name: localhost:3000

test:
  <<: *default
  secret_key_base: 533c2b6ed28fac8d074abd5a48bf7b1b975ac767e6722c74381e550813e17698330037755c37875525e0e7f876e820beb97da9976deeb95ec1db97c2823bed4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  google_analytics: <%= ENV["GOOGLE_ANALYTICS"] %>
